"""Resolve API spec dicts into C-specific render objects for Jinja2 templates."""

from ...states import State, current_state, resolve_states
from ...tools import apply_prefix as _apply_prefix
from ...tools import build_registry as _build_registry
from ...tools import resolve_enum_values
from .comments import DEFAULT_WIDTH
from .render import (
    CConstant,
    CEnum,
    CEnumValue,
    CField,
    CFuncPtr,
    CFuncPtrParam,
    CFunction,
    CModule,
    CParam,
    CStruct,
    CTypeDef,
    CUnionMember,
)


def _gating(d: dict, states: dict[str, State]) -> tuple[bool, str]:
    """How a construct's current state renders: (omitted, guard directive)."""
    name = current_state(d)
    state = states.get(name) if name else None
    if state is None or state.visibility == "always":
        return False, ""
    if state.visibility == "never":
        return True, ""
    if state.visibility == "opt_in":
        return False, f"#ifdef {state.guard}"
    return False, f"#ifndef {state.guard}"  # opt_out


def _default_banner(prefix: str) -> str:
    """Build a generic header banner, using an uppercased prefix as the name."""
    rule = f"//==={'-' * 70}===//"
    name = prefix.strip("_").upper() or "GENERATED"
    return "\n".join(
        [
            rule,
            "//",
            f"//                         {name}",
            "//",
            "//",
            rule,
            "//",
            "// !!!!!!!",
            "// WARNING: this file is autogenerated, manual changes will be overwritten",
            "// !!!!!!!",
        ]
    )


def resolve_c_options(
    metadata: dict,
    options: dict | None = None,
    states: dict[str, State] | None = None,
) -> dict:
    """Resolve C-adapter macro names, banner, and the comment column budget."""
    prefix = metadata.get("prefix", "")
    uprefix = prefix.upper()
    c = options or {}
    if states is None:
        states = resolve_states(metadata)
    # The legacy `deprecated` field gates with the deprecated state's token.
    # Without an opt_out deprecated state the gate never fires and the token
    # stays empty.
    dep = states.get("deprecated")
    dep_guard = dep.guard if dep and dep.visibility == "opt_out" else ""
    return {
        # Only decides `//!` line vs `/*! ... */` block; wrapping is the formatter's.
        "comment_width": c.get("comment_width", DEFAULT_WIDTH),
        "export_macro": c.get("export_macro", f"{uprefix}C_API"),
        "extension_export_macro": c.get(
            "extension_export_macro", f"{uprefix}EXTENSION_API"
        ),
        "deprecated_macro": c.get("deprecated_macro", f"{uprefix}DEPRECATED"),
        "emit_deprecated_attribute": bool(c.get("emit_deprecated_attribute", False)),
        "no_deprecated_guard": dep_guard,
        "typedef_guard_prefix": c.get("typedef_guard_prefix", f"{uprefix}TYPEDEF_"),
        "banner": c.get("banner", _default_banner(prefix)),
        "emit_v1_primitive_defs": bool(c.get("emit_v1_primitive_defs", False)),
        "emit_arrow_defs": bool(c.get("emit_arrow_defs", False)),
        "emit_extension_api": bool(c.get("emit_extension_api", False)),
    }


def resolve_modules(
    modules: list[dict],
    metadata: dict,
    options: dict | None = None,
    states: dict[str, State] | None = None,
) -> list[CModule]:
    """Transform validated API spec dicts into typed C render objects.

    `options` is the C adapter's options dict; other adapters that only need
    the function view may omit it. Pass `states` to reuse an already resolved
    vocabulary.
    """
    primitives = {p["name"]: p["c_type"] for p in metadata["primitives"]}
    suffixes = metadata["suffixes"]
    prefix = metadata.get("prefix", "")
    if states is None:
        states = resolve_states(metadata)
    c_options = options or {}
    handle_opts = c_options.get("handles", {})
    handle_style = handle_opts.get("default_style", "void_ptr")
    void_ptr_handles = frozenset(
        name
        for name, style in handle_opts.get("override_style", {}).items()
        if style == "void_ptr"
    )
    registry = _build_registry(modules, suffixes, prefix)
    return [
        _resolve_module(
            mod,
            registry,
            primitives,
            suffixes,
            states,
            prefix,
            handle_style,
            void_ptr_handles,
        )
        for mod in modules
    ]


def _is_tagged_struct(
    name: str, handle_style: str, void_ptr_handles: frozenset[str]
) -> bool:
    return handle_style == "tagged_struct" and name not in void_ptr_handles


# ---------------------------------------------------------------------------
# C name resolution
# ---------------------------------------------------------------------------


def _resolve_c_name(
    symbol: str,
    registry: dict[str, str],
    primitives: dict[str, str],
    context: str,
) -> str:
    """Resolve a spec symbol name to its C type string."""
    if symbol in primitives:
        return primitives[symbol]
    if symbol in registry:
        return registry[symbol]
    raise ValueError(f"{context}: unknown type '{symbol}'")


def _format_c_type(base: str, pointer: int = 0, is_const: bool = False) -> str:
    prefix = "const " if is_const else ""
    return f"{prefix}{base}{'*' * pointer}"


# ---------------------------------------------------------------------------
# Per-module resolution
# ---------------------------------------------------------------------------


def _resolve_module(
    mod: dict,
    registry: dict[str, str],
    primitives: dict[str, str],
    suffixes: dict[str, str],
    states: dict[str, State],
    prefix: str = "",
    handle_style: str = "void_ptr",
    void_ptr_handles: frozenset[str] = frozenset(),
) -> CModule:
    uprefix = prefix.upper()
    return CModule(
        name=mod["module"],
        types=(
            [
                _resolve_handle(
                    name,
                    h,
                    suffixes,
                    states,
                    prefix,
                    _is_tagged_struct(name, handle_style, void_ptr_handles),
                )
                for name, h in mod.get("handles", {}).items()
            ]
            + [
                _resolve_alias(name, a, registry, primitives, suffixes, states, prefix)
                for name, a in mod.get("aliases", {}).items()
            ]
        ),
        structs=[
            _resolve_struct(name, s, registry, primitives, suffixes, states, prefix)
            for name, s in mod.get("structs", {}).items()
        ],
        enums=[
            _resolve_enum(name, e, states, prefix)
            for name, e in mod.get("enums", {}).items()
        ],
        constants=[
            CConstant(
                name=f"{uprefix}{name}",
                value=c["value"],
                description=c.get("description", ""),
            )
            for name, c in mod.get("constants", {}).items()
        ],
        function_ptrs=[
            _resolve_callback(name, cb, registry, primitives, suffixes, states, prefix)
            for name, cb in mod.get("callbacks", {}).items()
        ],
        functions={
            f"{prefix}{fname}": _resolve_function(
                f"{prefix}{fname}", func, registry, primitives, states
            )
            for fname, func in mod.get("functions", {}).items()
        },
    )


def _resolve_handle(
    name: str,
    h: dict,
    suffixes: dict[str, str],
    states: dict[str, State],
    prefix: str = "",
    tagged_struct: bool = False,
) -> CTypeDef:
    prefixed = _apply_prefix(prefix, name)
    omitted, guard_directive = _gating(h, states)
    return CTypeDef(
        name=prefixed,
        canonical_name=f"{prefixed}{suffixes['handles']}",
        base="void",
        is_pointer=True,
        tagged_struct=tagged_struct,
        description=h.get("description", ""),
        omitted=omitted,
        guard_directive=guard_directive,
    )


def _resolve_alias(
    name: str,
    a: dict,
    registry: dict[str, str],
    primitives: dict[str, str],
    suffixes: dict[str, str],
    states: dict[str, State],
    prefix: str = "",
) -> CTypeDef:
    base = _resolve_c_name(a["underlying"], registry, primitives, f"Alias '{name}'")
    omitted, guard_directive = _gating(a, states)
    if a.get("qualified"):
        return CTypeDef(
            name=name,
            canonical_name=name,
            base=base,
            is_pointer=False,
            is_qualified=True,
            description=a.get("description", ""),
            omitted=omitted,
            guard_directive=guard_directive,
        )
    prefixed = _apply_prefix(prefix, name)
    return CTypeDef(
        name=prefixed,
        canonical_name=f"{prefixed}{suffixes['aliases']}",
        base=base,
        is_pointer=False,
        description=a.get("description", ""),
        omitted=omitted,
        guard_directive=guard_directive,
    )


def _resolve_field(
    f: dict,
    registry: dict[str, str],
    primitives: dict[str, str],
    context: str,
) -> CField:
    """Resolve one struct field: a leaf, an anonymous struct, or an anonymous union."""
    if "union" in f:
        return CField(
            name=f["name"],
            description=f.get("description", ""),
            union_members=[
                CUnionMember(
                    name=m["name"],
                    fields=[
                        _resolve_field(mf, registry, primitives, context)
                        for mf in m["fields"]
                    ],
                    description=m.get("description", ""),
                )
                for m in f["union"]
            ],
        )
    if "fields" in f:
        return CField(
            name=f["name"],
            description=f.get("description", ""),
            nested_fields=[
                _resolve_field(nf, registry, primitives, context) for nf in f["fields"]
            ],
        )
    base = _resolve_c_name(
        f["type"], registry, primitives, f"{context} field '{f['name']}'"
    )
    return CField(
        name=f["name"],
        base=base,
        pointer=f.get("pointer", 0),
        const=f.get("const", False),
        array_size=f.get("array_size"),
        description=f.get("description", ""),
    )


def _resolve_struct(
    name: str,
    s: dict,
    registry: dict[str, str],
    primitives: dict[str, str],
    suffixes: dict[str, str],
    states: dict[str, State],
    prefix: str = "",
) -> CStruct:
    prefixed = _apply_prefix(prefix, name)
    if s.get("pointer_alias"):
        alias = f"{prefixed}{suffixes['aliases']}"
    else:
        alias = prefixed

    fields = [
        _resolve_field(f, registry, primitives, f"Struct '{name}'")
        for f in s.get("fields", [])
    ]

    omitted, guard_directive = _gating(s, states)
    return CStruct(
        name=prefixed,
        template_alias=alias,
        pointer_alias=s.get("pointer_alias", False),
        fields=fields,
        description=s.get("description", ""),
        omitted=omitted,
        guard_directive=guard_directive,
    )


def _resolve_callback(
    name: str,
    cb: dict,
    registry: dict[str, str],
    primitives: dict[str, str],
    suffixes: dict[str, str],
    states: dict[str, State],
    prefix: str = "",
) -> CFuncPtr:
    prefixed = _apply_prefix(prefix, name)
    alias = f"{prefixed}{suffixes['callbacks']}"

    params = []
    for pname, p in cb.get("parameters", {}).items():
        base = _resolve_c_name(
            p["type"], registry, primitives, f"Callback '{name}' param '{pname}'"
        )
        params.append(
            CFuncPtrParam(
                name=pname,
                base=base,
                pointer=p["indirection"],
                const=p["const"],
            )
        )

    omitted, guard_directive = _gating(cb, states)
    return CFuncPtr(
        name=prefixed,
        template_alias=alias,
        return_base=_resolve_c_name(
            cb["return_type"], registry, primitives, f"Callback '{name}' return"
        ),
        return_pointer=cb["return_pointer"],
        return_const=cb["return_const"],
        params=params,
        description=cb.get("description", ""),
        omitted=omitted,
        guard_directive=guard_directive,
    )


def _resolve_function(
    fname: str,
    func: dict,
    registry: dict[str, str],
    primitives: dict[str, str],
    states: dict[str, State],
) -> CFunction:
    params: dict[str, CParam] = {}
    for pname, p in func["parameters"].items():
        base = _resolve_c_name(
            p["type"], registry, primitives, f"Function '{fname}' param '{pname}'"
        )
        c_decl = _format_c_type(base, p["indirection"], p["const"])
        params[pname] = CParam(
            name=pname,
            c_decl=c_decl,
            description=p.get("description") or None,
        )

    return_base = _resolve_c_name(
        func["return_type"], registry, primitives, f"Function '{fname}' return"
    )
    return_c = _format_c_type(return_base, func["return_pointer"], func["return_const"])

    state_name = current_state(func)
    if state_name == "deprecated":
        deprecated = func["lifecycle"][0][1]
    else:
        deprecated = func.get("deprecated") or None

    # A deprecated current state gates via its own guard directive; the legacy
    # `deprecated` field gates via the extra #ifndef wrap in the template, and
    # only when the declared states actually gate deprecation. This keeps the
    # rendered guards identical to what validate_semantics models.
    omitted, guard_directive = _gating(func, states)
    dep_state = states.get("deprecated")
    deprecated_gate = (
        bool(deprecated)
        and state_name != "deprecated"
        and dep_state is not None
        and dep_state.visibility == "opt_out"
    )

    return CFunction(
        name=fname,
        description=func.get("description") or None,
        deprecated=deprecated,
        return_c=return_c,
        static_inline=bool(func.get("static_inline", False)),
        omitted=omitted,
        guard_directive=guard_directive,
        deprecated_gate=deprecated_gate,
        parameters=params,
    )


def _resolve_enum(
    name: str,
    enum: dict,
    states: dict[str, State],
    prefix: str = "",
) -> CEnum:
    """Auto-number enum values via the shared helper."""
    uprefix = prefix.upper()
    c_name = _apply_prefix(prefix, name)
    resolved_values = {
        f"{uprefix}{vname}": CEnumValue(
            value=value,
            description=enum["values"][vname].get("description", ""),
        )
        for vname, value in resolve_enum_values(enum)
    }

    omitted, guard_directive = _gating(enum, states)
    return CEnum(
        name=c_name,
        description=enum.get("description", ""),
        values=resolved_values,
        omitted=omitted,
        guard_directive=guard_directive,
    )


def add_enum_sentinels(render_modules: list[CModule]) -> None:
    """Append the int-max sentinel to every emitted enum.

    The sentinel pins the underlying type to at least 32 bits, so the ABI
    stops depending on compiler flags like -fshort-enums. This is C-header
    policy: only the C adapter applies it, so the other adapters never see
    sentinel members or the collision check.
    """
    for mod in render_modules:
        for enum in mod.enums:
            if enum.omitted:
                continue
            sentinel = f"{enum.name.upper()}_MAX_ENUM"
            if sentinel in enum.values:
                raise ValueError(
                    f"Enum '{enum.name}': member '{sentinel}' collides with "
                    "the generated max-value sentinel"
                )
            enum.values[sentinel] = CEnumValue(value="0x7FFFFFFF")
