"""Tests for the C adapter's resolve layer (resolve.py + render.py).

These tests use hand-built dicts and do not depend on the real IDL,
so they remain valid after the spec moves to duckdb core.
"""

import pytest

from capigen.adapters.c.resolve import (
    add_enum_sentinels,
    resolve_c_options,
    resolve_modules,
    _format_c_type,
)
from capigen.adapters.c.render import (
    CConstant,
    CEnum,
    CEnumValue,
    CField,
    CFuncPtr,
    CFuncPtrParam,
    CFunction,
    CModule,
    CParam,
    CStruct,
    CTypeDef,
)


class TestFormatCType:
    def test_plain(self):
        assert _format_c_type("int32_t") == "int32_t"

    def test_pointer(self):
        assert _format_c_type("void", pointer=1) == "void*"

    def test_double_pointer(self):
        assert _format_c_type("char", pointer=2) == "char**"

    def test_const(self):
        assert _format_c_type("char", is_const=True) == "const char"

    def test_const_pointer(self):
        assert _format_c_type("char", pointer=1, is_const=True) == "const char*"


class TestResolveCOptions:
    def test_defaults_from_prefix(self):
        opts = resolve_c_options({"prefix": "duckdb_"})
        assert opts["export_macro"] == "DUCKDB_C_API"
        assert opts["extension_export_macro"] == "DUCKDB_EXTENSION_API"
        assert opts["deprecated_macro"] == "DUCKDB_DEPRECATED"
        assert opts["no_deprecated_guard"] == ""  # no states, no gate
        assert opts["typedef_guard_prefix"] == "DUCKDB_TYPEDEF_"

    def test_defaults_scale_with_prefix(self):
        opts = resolve_c_options({"prefix": "duckdb_v2_"})
        assert opts["export_macro"] == "DUCKDB_V2_C_API"
        assert opts["typedef_guard_prefix"] == "DUCKDB_V2_TYPEDEF_"

    def test_empty_prefix(self):
        opts = resolve_c_options({})
        assert opts["export_macro"] == "C_API"

    def test_default_banner_derives_name_from_prefix(self):
        opts = resolve_c_options({"prefix": "myapi_"})
        assert "MYAPI" in opts["banner"]
        assert "autogenerated" in opts["banner"]

    def test_explicit_options_honored(self):
        meta = {"prefix": "duckdb_"}
        opts = resolve_c_options(
            meta,
            {
                "export_macro": "MY_API",
                "extension_export_macro": "MY_EXT_API",
                "deprecated_macro": "MY_DEPRECATED",
                "typedef_guard_prefix": "MY_TYPEDEF_",
                "banner": "// custom banner",
            },
        )
        assert opts["export_macro"] == "MY_API"
        assert opts["extension_export_macro"] == "MY_EXT_API"
        assert opts["deprecated_macro"] == "MY_DEPRECATED"
        assert opts["typedef_guard_prefix"] == "MY_TYPEDEF_"
        assert opts["banner"] == "// custom banner"

    def test_no_deprecated_guard_from_declared_states(self):
        """The legacy deprecated gate uses the declared deprecated state's guard."""
        meta = {
            "prefix": "duckdb_",
            "lifecycle_states": {
                "deprecated": {"visibility": "opt_out", "guard": "MY_DEP"}
            },
        }
        assert resolve_c_options(meta)["no_deprecated_guard"] == "MY_DEP"


class TestResolveHandles:
    def test_handle(self, metadata, make_module):
        modules = [make_module("m", handles={"duckdb_conn": {}})]
        result = resolve_modules(modules, metadata)
        t = result[0].types[0]
        assert isinstance(t, CTypeDef)
        assert t.name == "duckdb_conn"
        assert t.canonical_name == "duckdb_conn_ptr"
        assert t.base == "void"
        assert t.is_pointer is True

    def test_handle_with_description(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                handles={
                    "ctx": {"description": "A context handle"},
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].types[0].canonical_name == "ctx_ptr"


class TestResolveAliases:
    def test_alias_to_primitive(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                aliases={
                    "duckdb_idx": {"underlying": "u64"},
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        t = result[0].types[0]
        assert isinstance(t, CTypeDef)
        assert t.canonical_name == "duckdb_idx_t"
        assert t.base == "uint64_t"
        assert t.is_pointer is False

    def test_alias_to_alias(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                aliases={
                    "err_code": {"underlying": "u32"},
                    "api_call": {"underlying": "err_code"},
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        api_call = result[0].types[1]
        assert api_call.base == "err_code_t"

    def test_alias_to_handle(self, metadata, make_module):
        modules = [
            make_module("common", handles={"ctx": {}}),
            make_module("m", aliases={"my_ctx": {"underlying": "ctx"}}),
        ]
        result = resolve_modules(modules, metadata)
        alias = result[1].types[0]
        assert alias.base == "ctx_ptr"


class TestResolveStructs:
    def test_struct_basic(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "my_struct": {
                        "fields": [
                            {
                                "name": "data",
                                "type": "opaque",
                                "pointer": 1,
                                "const": False,
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        s = result[0].structs[0]
        assert isinstance(s, CStruct)
        assert s.template_alias == "my_struct"
        assert s.pointer_alias is False
        assert isinstance(s.fields[0], CField)
        assert s.fields[0].base == "void"
        assert s.fields[0].pointer == 1

    def test_struct_with_pointer_alias(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "my_struct": {
                        "pointer_alias": True,
                        "fields": [
                            {
                                "name": "val",
                                "type": "i32",
                                "pointer": 0,
                                "const": False,
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        s = result[0].structs[0]
        assert s.template_alias == "my_struct_t"
        assert s.pointer_alias is True

    def test_struct_with_multiple_fields(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "pair": {
                        "fields": [
                            {
                                "name": "first",
                                "type": "i32",
                                "pointer": 0,
                                "const": False,
                            },
                            {
                                "name": "second",
                                "type": "u64",
                                "pointer": 0,
                                "const": False,
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        s = result[0].structs[0]
        assert len(s.fields) == 2
        assert s.fields[0].name == "first"
        assert s.fields[1].name == "second"

    def test_struct_const_field(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "s": {
                        "fields": [
                            {
                                "name": "name",
                                "type": "char",
                                "pointer": 1,
                                "const": True,
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        f = result[0].structs[0].fields[0]
        assert f.const is True
        assert f.pointer == 1

    def test_struct_nested_struct_field(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "outer": {
                        "fields": [
                            {
                                "name": "inner",
                                "fields": [
                                    {"name": "a", "type": "i32"},
                                    {"name": "b", "type": "u64"},
                                ],
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        f = result[0].structs[0].fields[0]
        assert f.name == "inner"
        assert f.base == ""
        assert f.union_members is None
        assert f.nested_fields is not None
        assert [nf.name for nf in f.nested_fields] == ["a", "b"]
        assert f.nested_fields[0].base == "int32_t"
        assert f.nested_fields[1].base == "uint64_t"

    def test_struct_union_field(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "string": {
                        "fields": [
                            {
                                "name": "value",
                                "union": [
                                    {
                                        "name": "pointer",
                                        "fields": [
                                            {"name": "length", "type": "u32"},
                                            {
                                                "name": "prefix",
                                                "type": "char",
                                                "array_size": 4,
                                            },
                                            {
                                                "name": "ptr",
                                                "type": "char",
                                                "pointer": 1,
                                            },
                                        ],
                                    },
                                    {
                                        "name": "inlined",
                                        "fields": [
                                            {"name": "length", "type": "u32"},
                                            {
                                                "name": "inlined",
                                                "type": "char",
                                                "array_size": 12,
                                            },
                                        ],
                                    },
                                ],
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        f = result[0].structs[0].fields[0]
        assert f.name == "value"
        assert f.nested_fields is None
        assert f.union_members is not None
        assert [m.name for m in f.union_members] == ["pointer", "inlined"]
        pointer = f.union_members[0]
        assert [mf.name for mf in pointer.fields] == ["length", "prefix", "ptr"]
        assert pointer.fields[1].array_size == 4
        assert pointer.fields[2].pointer == 1
        inlined = f.union_members[1]
        assert inlined.fields[1].base == "char"
        assert inlined.fields[1].array_size == 12

    def test_struct_inline_array_field(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "my_struct": {
                        "fields": [
                            {
                                "name": "buf",
                                "type": "char",
                                "pointer": 0,
                                "const": False,
                                "array_size": 64,
                            },
                            {
                                "name": "code",
                                "type": "u32",
                                "pointer": 0,
                                "const": False,
                            },
                        ],
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        fields = result[0].structs[0].fields
        assert fields[0].array_size == 64
        assert fields[0].pointer == 0
        assert fields[1].array_size is None


class TestResolveCallbacks:
    def test_callback(self, metadata, make_module):
        modules = [
            make_module("common", handles={"ctx": {}}),
            make_module(
                "m",
                callbacks={
                    "my_callback": {
                        "return_type": "opaque",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {
                            "context": {
                                "type": "ctx",
                                "indirection": 0,
                                "const": False,
                            },
                            "value": {
                                "type": "i32",
                                "indirection": 0,
                                "const": False,
                            },
                        },
                    },
                },
            ),
        ]
        result = resolve_modules(modules, metadata)
        fp = result[1].function_ptrs[0]
        assert isinstance(fp, CFuncPtr)
        assert fp.template_alias == "my_callback_cb"
        assert fp.return_base == "void"
        assert len(fp.params) == 2
        assert isinstance(fp.params[0], CFuncPtrParam)
        assert fp.params[0].base == "ctx_ptr"
        assert fp.params[1].base == "int32_t"

    def test_callback_with_pointer_return(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                callbacks={
                    "getter": {
                        "return_type": "char",
                        "return_pointer": 1,
                        "return_const": True,
                        "parameters": {},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        fp = result[0].function_ptrs[0]
        assert fp.return_base == "char"
        assert fp.return_pointer == 1
        assert fp.return_const is True

    def test_callback_no_params(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                callbacks={
                    "simple": {
                        "return_type": "opaque",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].function_ptrs[0].params == []


class TestResolveFunctions:
    def test_function_with_all_fields(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "do_thing": {
                        "description": "Longer description",
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {
                            "name": {
                                "type": "char",
                                "indirection": 1,
                                "const": True,
                            },
                            "count": {
                                "type": "u64",
                                "indirection": 0,
                                "const": False,
                            },
                        },
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        f = result[0].functions["do_thing"]
        assert isinstance(f, CFunction)
        assert f.description == "Longer description"
        assert f.return_c == "int32_t"
        assert isinstance(f.parameters["name"], CParam)
        assert f.parameters["name"].c_decl == "const char*"
        assert f.parameters["count"].c_decl == "uint64_t"

    def test_function_with_out_parameter(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "get_value": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {
                            "out_val": {
                                "type": "u64",
                                "indirection": 1,
                                "const": False,
                                "kind": "OUT",
                            },
                        },
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        p = result[0].functions["get_value"].parameters["out_val"]
        assert p.c_decl == "uint64_t*"

    def test_function_with_pointer_return(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "get_str": {
                        "return_type": "char",
                        "return_pointer": 1,
                        "return_const": True,
                        "parameters": {},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].functions["get_str"].return_c == "const char*"

    def test_function_no_params(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "noop": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].functions["noop"].parameters == {}

    def test_deprecated_function(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "old_func": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "deprecated": "v1.0.0",
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].functions["old_func"].deprecated == "v1.0.0"

    def test_param_description(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {
                            "p": {
                                "type": "i32",
                                "indirection": 0,
                                "const": False,
                                "description": "the param",
                            },
                        },
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].functions["f"].parameters["p"].description == "the param"

    def test_unknown_type_raises(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "bad": {
                        "return_type": "nonexistent",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                    },
                },
            )
        ]
        with pytest.raises(ValueError, match="unknown type 'nonexistent'"):
            resolve_modules(modules, metadata)


class TestResolveEnums:
    def test_auto_numbering(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                enums={
                    "MY_ENUM": {
                        "description": "Test enum",
                        "values": {"A": {}, "B": {}, "C": {}},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        e = result[0].enums[0]
        assert isinstance(e, CEnum)
        assert isinstance(e.values["A"], CEnumValue)
        assert e.values["A"].value == 0
        assert e.values["B"].value == 1
        assert e.values["C"].value == 2

    def test_explicit_value_resets_counter(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                enums={
                    "MY_ENUM": {
                        "description": "",
                        "values": {"A": {}, "B": {"value": 10}, "C": {}},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        e = result[0].enums[0]
        assert e.values["A"].value == 0
        assert e.values["B"].value == 10
        assert e.values["C"].value == 11

    def test_enum_description(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                enums={
                    "E": {"description": "A test enum", "values": {"X": {}}},
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].enums[0].description == "A test enum"

    def test_enum_value_description(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                enums={
                    "E": {
                        "description": "",
                        "values": {"X": {"description": "the X value"}},
                    },
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].enums[0].values["X"].description == "the X value"


class TestResolveConstants:
    def test_integer_constant(self, metadata, make_module):
        modules = [make_module("m", constants={"MAX_SIZE": {"value": 1024}})]
        result = resolve_modules(modules, metadata)
        c = result[0].constants[0]
        assert isinstance(c, CConstant)
        assert c.name == "MAX_SIZE"
        assert c.value == 1024

    def test_string_constant(self, metadata, make_module):
        modules = [make_module("m", constants={"VERSION": {"value": '"1.0"'}})]
        result = resolve_modules(modules, metadata)
        assert result[0].constants[0].value == '"1.0"'

    def test_constant_description(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                constants={
                    "X": {"value": 42, "description": "the answer"},
                },
            )
        ]
        result = resolve_modules(modules, metadata)
        assert result[0].constants[0].description == "the answer"


class TestResolveModule:
    def test_returns_cmodule(self, metadata, make_module):
        modules = [make_module("test_mod")]
        result = resolve_modules(modules, metadata)
        assert len(result) == 1
        assert isinstance(result[0], CModule)
        assert result[0].name == "test_mod"

    def test_cross_module_type_resolution(self, metadata, make_module):
        """Types declared in one module are available in another's functions."""
        modules = [
            make_module("common", handles={"handle": {}}),
            make_module(
                "api",
                functions={
                    "use_handle": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {
                            "h": {
                                "type": "handle",
                                "indirection": 0,
                                "const": False,
                            },
                        },
                    },
                },
            ),
        ]
        result = resolve_modules(modules, metadata)
        f = result[1].functions["use_handle"]
        assert f.parameters["h"].c_decl == "handle_ptr"

    def test_empty_module(self, metadata, make_module):
        modules = [make_module("empty")]
        result = resolve_modules(modules, metadata)
        m = result[0]
        assert m.types == []
        assert m.structs == []
        assert m.enums == []
        assert m.constants == []
        assert m.function_ptrs == []
        assert m.functions == {}


UNSTABLE = [["unstable", "v1.0.0", "2026-01-01"]]


class TestStateGating:
    """The current (top) status entry decides omission and the guard directive."""

    def test_unstable_handle_gets_opt_in_directive(self, metadata, make_module):
        modules = [make_module("m", handles={"h": {"lifecycle": UNSTABLE}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == "#ifdef API_UNSTABLE"
        assert t.omitted is False

    def test_no_status_is_visible(self, metadata, make_module):
        modules = [make_module("m", handles={"h": {}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == ""
        assert t.omitted is False

    def test_stabilized_history_is_visible(self, metadata, make_module):
        """An older unstable entry below a stable top entry does not gate."""
        status = [
            ["stable", "v1.1.0", "2026-06-01"],
            ["unstable", "v1.0.0", "2026-01-01"],
        ]
        modules = [make_module("m", handles={"h": {"lifecycle": status}})]
        assert resolve_modules(modules, metadata)[0].types[0].guard_directive == ""

    def test_removed_handle_is_omitted(self, metadata, make_module):
        status = [["removed", "v1.0.0", "2026-01-01"]]
        modules = [make_module("m", handles={"h": {"lifecycle": status}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.omitted is True
        assert t.guard_directive == ""

    def test_deprecated_handle_gets_opt_out_directive(self, metadata, make_module):
        status = [["deprecated", "v1.1.0", "2026-06-01"]]
        modules = [make_module("m", handles={"h": {"lifecycle": status}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == "#ifndef API_NO_DEPRECATED"

    def test_declared_states_supply_the_guard(self, metadata, make_module):
        metadata["lifecycle_states"] = {
            "unstable": {"visibility": "opt_in", "guard": "MY_GUARD"}
        }
        modules = [make_module("m", handles={"h": {"lifecycle": UNSTABLE}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == "#ifdef MY_GUARD"

    def test_unknown_state_is_visible_at_resolve_time(self, metadata, make_module):
        """Resolve is lenient; validate_semantics rejects the unknown name."""
        status = [["experimental", "v1.0.0", "2026-01-01"]]
        modules = [make_module("m", handles={"h": {"lifecycle": status}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == ""
        assert t.omitted is False

    def test_qualified_alias_gets_directive(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                aliases={
                    "idx_t": {
                        "underlying": "u64",
                        "qualified": True,
                        "lifecycle": UNSTABLE,
                    }
                },
            )
        ]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == "#ifdef API_UNSTABLE"

    def test_struct_callback_enum_get_directives(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                structs={
                    "s": {
                        "fields": [
                            {"name": "f", "type": "u32", "pointer": 0, "const": False}
                        ],
                        "lifecycle": UNSTABLE,
                    }
                },
                callbacks={
                    "cb": {
                        "return_type": "opaque",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "lifecycle": UNSTABLE,
                    }
                },
                enums={"E": {"values": {"A": {}}, "lifecycle": UNSTABLE}},
            )
        ]
        m = resolve_modules(modules, metadata)[0]
        assert m.structs[0].guard_directive == "#ifdef API_UNSTABLE"
        assert m.function_ptrs[0].guard_directive == "#ifdef API_UNSTABLE"
        assert m.enums[0].guard_directive == "#ifdef API_UNSTABLE"

    def test_unstable_function(self, metadata, make_module):
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "lifecycle": UNSTABLE,
                    }
                },
            )
        ]
        f = resolve_modules(modules, metadata)[0].functions["f"]
        assert f.guard_directive == "#ifdef API_UNSTABLE"
        assert f.deprecated is None
        assert f.deprecated_gate is False

    def test_deprecated_by_status_uses_directive_not_gate(self, metadata, make_module):
        status = [["deprecated", "v1.1.0", "2026-06-01"]]
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "lifecycle": status,
                    }
                },
            )
        ]
        f = resolve_modules(modules, metadata)[0].functions["f"]
        assert f.guard_directive == "#ifndef API_NO_DEPRECATED"
        assert f.deprecated == "v1.1.0"
        assert f.deprecated_gate is False

    def test_legacy_deprecated_field_uses_gate_not_directive(
        self, metadata, make_module
    ):
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "deprecated": "v1.0.0",
                    }
                },
            )
        ]
        f = resolve_modules(modules, metadata)[0].functions["f"]
        assert f.guard_directive == ""
        assert f.deprecated == "v1.0.0"
        assert f.deprecated_gate is True

    def test_legacy_deprecated_without_opt_out_state_is_ungated(
        self, metadata, make_module
    ):
        """No opt_out deprecated state declared: the legacy field gates nothing."""
        metadata["lifecycle_states"] = {"live": {"visibility": "always"}}
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "deprecated": "v1.0.0",
                    }
                },
            )
        ]
        f = resolve_modules(modules, metadata)[0].functions["f"]
        assert f.deprecated_gate is False
        assert f.guard_directive == ""

    def test_legacy_deprecated_with_visible_deprecated_state_is_ungated(
        self, metadata, make_module
    ):
        metadata["lifecycle_states"] = {"deprecated": {"visibility": "always"}}
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "deprecated": "v1.0.0",
                    }
                },
            )
        ]
        f = resolve_modules(modules, metadata)[0].functions["f"]
        assert f.deprecated_gate is False

    def test_no_states_block_means_no_states(self, metadata, make_module):
        """Without a states block nothing gates; validate rejects the status."""
        del metadata["lifecycle_states"]
        modules = [make_module("m", handles={"h": {"lifecycle": UNSTABLE}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == ""
        assert t.omitted is False

    def test_empty_states_map_disables_all_gating(self, metadata, make_module):
        """states: {} declares no states at all; everything renders visible."""
        metadata["lifecycle_states"] = {}
        modules = [make_module("m", handles={"h": {"lifecycle": UNSTABLE}})]
        t = resolve_modules(modules, metadata)[0].types[0]
        assert t.guard_directive == ""
        assert t.omitted is False

    def test_removed_function_is_omitted(self, metadata, make_module):
        status = [["removed", "v1.1.0", "2026-06-01"]]
        modules = [
            make_module(
                "m",
                functions={
                    "f": {
                        "return_type": "i32",
                        "return_pointer": 0,
                        "return_const": False,
                        "parameters": {},
                        "lifecycle": status,
                    }
                },
            )
        ]
        assert resolve_modules(modules, metadata)[0].functions["f"].omitted is True


class TestEnumMaxSentinel:
    """The C adapter appends an int-max member that pins each enum's width."""

    def _enum(self, metadata, make_module, enums, sentinels=True):
        modules = [make_module("m", enums=enums)]
        render = resolve_modules(modules, metadata)
        if sentinels:
            add_enum_sentinels(render)
        return render[0].enums[0]

    def test_resolve_is_sentinel_free(self, metadata, make_module):
        """Shared resolution never adds sentinels; only the C post-step does."""
        e = self._enum(
            metadata, make_module, {"MODE": {"values": {"A": {}}}}, sentinels=False
        )
        assert list(e.values) == ["A"]

    def test_sentinel_is_last_with_int_max_value(self, metadata, make_module):
        e = self._enum(metadata, make_module, {"MODE": {"values": {"A": {}, "B": {}}}})
        assert list(e.values) == ["A", "B", "MODE_MAX_ENUM"]
        assert e.values["MODE_MAX_ENUM"].value == "0x7FFFFFFF"

    def test_sentinel_does_not_disturb_auto_numbering(self, metadata, make_module):
        e = self._enum(metadata, make_module, {"MODE": {"values": {"A": {}, "B": {}}}})
        assert e.values["A"].value == 0
        assert e.values["B"].value == 1

    def test_sentinel_name_uses_prefixed_enum_name(self, metadata, make_module):
        metadata["prefix"] = "duckdb_v2_"
        e = self._enum(metadata, make_module, {"MODE": {"values": {"A": {}}}})
        assert "DUCKDB_V2_MODE_MAX_ENUM" in e.values

    def test_sentinel_of_lowercase_enum_is_macro_case(self, metadata, make_module):
        metadata["prefix"] = "lib_"
        e = self._enum(metadata, make_module, {"mode": {"values": {"A": {}}}})
        assert "LIB_MODE_MAX_ENUM" in e.values

    def test_omitted_enum_gets_no_sentinel_and_no_collision_error(
        self, metadata, make_module
    ):
        """A removed enum is never rendered, so a sentinel-like member is fine."""
        e = self._enum(
            metadata,
            make_module,
            {
                "MODE": {
                    "values": {"MODE_MAX_ENUM": {}},
                    "lifecycle": [["removed", "v1.0.0", "2026-01-01"]],
                }
            },
        )
        assert e.omitted is True
        assert list(e.values) == ["MODE_MAX_ENUM"]

    def test_colliding_member_name_raises(self, metadata, make_module):
        with pytest.raises(ValueError, match="collides with"):
            self._enum(
                metadata, make_module, {"MODE": {"values": {"MODE_MAX_ENUM": {}}}}
            )
