"""Bridge adapter: generates C++ stub implementations for unimplemented V2 C API functions.

Scans existing source files in a target directory for already-implemented functions,
then generates stubs only for the remainder. Re-running is safe and idempotent.
"""

import re
from pathlib import Path

from ..c.resolve import resolve_c_options, resolve_modules


def _scan_implemented_functions(scan_dir: Path, prefix: str) -> set[str]:
    """Find function names already implemented in .cpp files."""
    implemented: set[str] = set()
    if not scan_dir.is_dir():
        return implemented

    pattern = re.compile(rf"\b{re.escape(prefix)}\w+\s*\(")
    for cpp_file in scan_dir.glob("*.cpp"):
        if cpp_file.name == "capi_v2_stubs.cpp":
            continue  # skip the stubs file itself
        content = cpp_file.read_text()
        for match in pattern.finditer(content):
            fname = match.group(0).rstrip("(").strip()
            implemented.add(fname)

    return implemented


def generate(
    modules: list[dict],
    metadata: dict,
    output_path: Path,
    scan_dir: Path | None = None,
    invocation: str | None = None,
) -> None:
    """Generate C++ stub file for unimplemented V2 C API functions."""
    render_modules = resolve_modules(modules, metadata)

    prefix = metadata.get("prefix", "")
    bridge_opts = metadata.get("options", {}).get("bridge", {})
    stub_return = bridge_opts.get("stub_return", f"{prefix.upper()}API_ERROR")
    include = bridge_opts.get("include")

    implemented = _scan_implemented_functions(scan_dir, prefix) if scan_dir else set()

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by capigen bridge adapter -- do not edit.")
    if invocation:
        lines.append(f"// Re-run: {invocation}")
    lines.append("")
    # Engine side: implement the full surface, so opt in to unstable declarations.
    unstable_guard = resolve_c_options(metadata)["unstable_guard"]
    lines.append(f"#ifndef {unstable_guard}")
    lines.append(f"#define {unstable_guard}")
    lines.append("#endif")
    lines.append("")
    if include:
        lines.append(f'#include "{include}"')
        lines.append("")

    stub_count = 0
    for mod in render_modules:
        for fname, func in mod.functions.items():
            if fname in implemented or func.static_inline:
                continue

            # Build parameter list
            params = []
            for pname, param in func.parameters.items():
                params.append(f"{param.c_decl} {pname}")
            param_str = ", ".join(params) if params else "void"

            lines.append(f"{func.return_c} {fname}({param_str}) {{")
            lines.append(f"\treturn {stub_return}; // Not yet implemented")
            lines.append("}")
            lines.append("")
            stub_count += 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(
        f"Generated {output_path} ({stub_count} stubs, "
        f"{len(implemented)} already implemented)"
    )
