"""Bridge adapter: generates C++ stub implementations for unimplemented V2 C API functions.

Scans existing source files in a target directory for already-implemented functions,
then generates stubs only for the remainder. Re-running is safe and idempotent.
"""

import re
from pathlib import Path

from ...states import resolve_states
from ..c.resolve import resolve_modules


def _scan_implemented_functions(scan_dir: Path, prefix: str) -> set[str]:
    """Find function names already implemented in .cpp files."""
    implemented: set[str] = set()
    if not scan_dir.is_dir():
        return implemented

    pattern = re.compile(rf"\b{re.escape(prefix)}\w+\s*\(")
    for cpp_file in scan_dir.glob("*.cpp"):
        if cpp_file.name == "capi_v2_stubs.cpp":
            continue  # skip the stubs file itself
        content = cpp_file.read_text()
        for match in pattern.finditer(content):
            fname = match.group(0).rstrip("(").strip()
            implemented.add(fname)

    return implemented


def generate(
    modules: list[dict],
    metadata: dict,
    output_path: Path,
    scan_dir: Path | None = None,
    invocation: str | None = None,
) -> None:
    """Generate C++ stub file for unimplemented V2 C API functions."""
    render_modules = resolve_modules(modules, metadata)

    prefix = metadata.get("prefix", "")
    bridge_opts = metadata.get("options", {}).get("bridge", {})
    stub_return = bridge_opts.get("stub_return")
    include = bridge_opts.get("include_header")

    implemented = _scan_implemented_functions(scan_dir, prefix) if scan_dir else set()

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by capigen bridge adapter -- do not edit.")
    if invocation:
        lines.append(f"// Re-run: {invocation}")
    lines.append("")
    # Engine side: implement the full surface, so opt in to every gated state.
    opt_in_guards = sorted(
        {s.guard for s in resolve_states(metadata).values() if s.visibility == "opt_in"}
    )
    for guard in opt_in_guards:
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}")
        lines.append("#endif")
    if opt_in_guards:
        lines.append("")
    if include:
        lines.append(f'#include "{include}"')
        lines.append("")

    to_stub = [
        (fname, func)
        for mod in render_modules
        for fname, func in mod.functions.items()
        if fname not in implemented and not func.static_inline and not func.omitted
    ]
    # No universal error value exists across specs, so the return expression
    # must be configured whenever there is anything to stub.
    if to_stub and not stub_return:
        raise ValueError(
            "bridge requires options.bridge.stub_return when stubs are generated"
        )

    for fname, func in to_stub:
        params = [f"{param.c_decl} {pname}" for pname, param in func.parameters.items()]
        param_str = ", ".join(params) if params else "void"

        lines.append(f"{func.return_c} {fname}({param_str}) {{")
        lines.append(f"\treturn {stub_return}; // Not yet implemented")
        lines.append("}")
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(
        f"Generated {output_path} ({len(to_stub)} stubs, "
        f"{len(implemented)} already implemented)"
    )
