"""Bridge adapter: generates C++ stub implementations for unimplemented V2 C API functions.

Scans existing source files in a target directory for already-implemented functions,
then generates stubs only for the remainder. Re-running is safe and idempotent.
"""

import re
from pathlib import Path

from ..c.resolve import resolve_modules


def _scan_implemented_functions(scan_dir: Path) -> set[str]:
    """Find function names already implemented in .cpp files."""
    implemented: set[str] = set()
    if not scan_dir.is_dir():
        return implemented

    pattern = re.compile(r"\bduckdb_v2_\w+\s*\(")
    for cpp_file in scan_dir.glob("*.cpp"):
        if cpp_file.name == "capi_v2_stubs.cpp":
            continue  # skip the stubs file itself
        content = cpp_file.read_text()
        for match in pattern.finditer(content):
            fname = match.group(0).rstrip("(").strip()
            implemented.add(fname)

    return implemented


def generate(
    modules: list[dict], metadata: dict, output_path: Path, scan_dir: Path | None = None
) -> None:
    """Generate C++ stub file for unimplemented V2 C API functions."""
    render_modules = resolve_modules(modules, metadata)

    implemented = _scan_implemented_functions(scan_dir) if scan_dir else set()

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by capigen bridge adapter -- do not edit.")
    lines.append(
        "// Re-run: cd capiv2 && uv run capigen bridge "
        "--scan-dir ../src/main/capi_v2 -o ../src/main/capi_v2/capi_v2_stubs.cpp"
    )
    lines.append("")
    lines.append('#include "capi_v2_internal.hpp"')
    lines.append("")

    stub_count = 0
    for mod in render_modules:
        for fname, func in mod.functions.items():
            if fname in implemented:
                continue

            # Build parameter list
            params = []
            for pname, param in func.parameters.items():
                params.append(f"{param.c_decl} {pname}")
            param_str = ", ".join(params) if params else "void"

            lines.append(f"{func.return_c} {fname}({param_str}) {{")
            lines.append("\treturn DUCKDB_V2_API_ERROR; // Not yet implemented")
            lines.append("}")
            lines.append("")
            stub_count += 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(
        f"Generated {output_path} ({stub_count} stubs, "
        f"{len(implemented)} already implemented)"
    )
